FROM python:3.10-slim

WORKDIR /src

COPY . /src

# uncomment line 8 and 9 if this app will need to use 3rd party library
# RUN pip install --upgrade pip
# RUN pip install -r src/requirements.txt

CMD ["python", "src/main.py"]
